In [1]:
import pandas as pd

In [2]:
lucas_file = "LUCAS-SOIL-2018.csv"

In [3]:
df = pd.read_csv(lucas_file, sep = ",", header = "infer")

In [4]:
df.columns

Index(['Depth', 'POINTID', 'pH_CaCl2', 'pH_H2O', 'EC', 'OC', 'CaCO3', 'P', 'N',
       'K', 'OC (20-30 cm)', 'CaCO3 (20-30 cm)', 'Ox_Al', 'Ox_Fe', 'NUTS_0',
       'NUTS_1', 'NUTS_2', 'NUTS_3', 'TH_LAT', 'TH_LONG', 'SURVEY_DATE',
       'Elev', 'LC', 'LU', 'LC0_Desc', 'LC1_Desc', 'LU1_Desc'],
      dtype='object')

In [5]:
df.head(n = 11)

,Depth,POINTID,pH_CaCl2,pH_H2O,EC,OC,CaCO3,P,N,K,...,NUTS_3,TH_LAT,TH_LONG,SURVEY_DATE,Elev,LC,LU,LC0_Desc,LC1_Desc,LU1_Desc
0,0-20 cm,47862690,4.1,4.81,8.73,12.4,3,< LOD,1.1,101.9,...,AT113,47.150238,16.134212,06-07-18,291,C23,U120,Woodland,Other coniferous woodland,Forestry
1,0-20 cm,47882704,4.1,4.93,5.06,16.7,1,< LOD,1.3,51.2,...,AT113,47.274272,16.175359,06-07-18,373,C21,U120,Woodland,Spruce dominated coniferous woodland,Forestry
2,0-20 cm,47982688,4.1,4.85,12.53,47.5,1,12.3,3.1,114.8,...,AT113,47.123260,16.289693,02-06-18,246,C33,U120,Woodland,Other mixed woodland,Forestry
3,0-20 cm,48022702,5.5,5.80,21.10,28.1,3,< LOD,2,165.8,...,AT113,47.245693,16.357506,06-07-18,305,C22,U120,Woodland,Pine dominated coniferous woodland,Forestry
4,0-20 cm,48062708,6.1,6.48,10.89,19.4,2,< LOD,2.2,42.1,...,AT113,47.296372,16.416782,05-07-18,335,C22,U120,Woodland,Pine dominated coniferous woodland,Forestry
5,0-20 cm,48122730,6.3,6.81,14.46,18,NaN,68,2,277.2,...,AT111,47.488817,16.520595,18-06-18,232,B18,U111,Cropland,Triticale,Agriculture (excluding fallow land and kitchen...
6,0-20 cm,48202738,5.8,6.37,17.08,12.5,NaN,58.1,1.4,315.5,...,AT111,47.554102,16.635559,18-06-18,283,B32,U111,Cropland,Rape and turnip rape,Agriculture (excluding fallow land and kitchen...
7,0-20 cm,48222780,7.1,7.98,23.55,22.9,96,17.5,2.1,329.1,...,AT112,47.928696,16.711158,21-05-18,136,B82,U111,Cropland,Vineyards,Agriculture (excluding fallow land and kitchen...
8,0-20 cm,48342774,7.4,8.09,22.61,29.1,86,62.2,2.9,367.8,...,AT112,47.865059,16.863852,26-06-18,115,B32,U111,Cropland,Rape and turnip rape,Agriculture (excluding fallow land and kitchen...
9,0-20 cm,48442784,7.2,7.84,14.94,14.4,3,< LOD,1.6,146.2,...,AT112,47.946158,17.009260,11-06-18,166,B14,U111,Cropland,Rye,Agriculture (excluding fallow land and kitchen...
10,0-20 cm,48462776,7.6,8.15,30.90,21.8,112,22.3,2,220.2,...,AT112,47.872833,17.026032,14-05-18,140,B13,U111,Cropland,Barley,Agriculture (excluding fallow land and kitchen...

In [6]:
df.head()

,Depth,POINTID,pH_CaCl2,pH_H2O,EC,OC,CaCO3,P,N,K,...,NUTS_3,TH_LAT,TH_LONG,SURVEY_DATE,Elev,LC,LU,LC0_Desc,LC1_Desc,LU1_Desc
0,0-20 cm,47862690,4.1,4.81,8.73,12.4,3,< LOD,1.1,101.9,...,AT113,47.150238,16.134212,06-07-18,291,C23,U120,Woodland,Other coniferous woodland,Forestry
1,0-20 cm,47882704,4.1,4.93,5.06,16.7,1,< LOD,1.3,51.2,...,AT113,47.274272,16.175359,06-07-18,373,C21,U120,Woodland,Spruce dominated coniferous woodland,Forestry
2,0-20 cm,47982688,4.1,4.85,12.53,47.5,1,12.3,3.1,114.8,...,AT113,47.123260,16.289693,02-06-18,246,C33,U120,Woodland,Other mixed woodland,Forestry
3,0-20 cm,48022702,5.5,5.80,21.10,28.1,3,< LOD,2,165.8,...,AT113,47.245693,16.357506,06-07-18,305,C22,U120,Woodland,Pine dominated coniferous woodland,Forestry
4,0-20 cm,48062708,6.1,6.48,10.89,19.4,2,< LOD,2.2,42.1,...,AT113,47.296372,16.416782,05-07-18,335,C22,U120,Woodland,Pine dominated coniferous woodland,Forestry

In [7]:
df.columns[1]

'POINTID'

In [14]:
df.dtypes

Depth                object
POINTID               int64
pH_CaCl2            float64
pH_H2O              float64
EC                  float64
OC                   object
CaCO3                object
P                    object
N                    object
K                    object
OC (20-30 cm)        object
CaCO3 (20-30 cm)    float64
Ox_Al               float64
Ox_Fe               float64
NUTS_0               object
NUTS_1               object
NUTS_2               object
NUTS_3               object
TH_LAT              float64
TH_LONG             float64
SURVEY_DATE          object
Elev                  int64
LC                   object
LU                   object
LC0_Desc             object
LC1_Desc             object
LU1_Desc             object
dtype: object

In [9]:
type(df.dtypes)

pandas.core.series.Series

In [10]:
#To know how many rows and columns (rows, columns)
df.shape

(18984, 27)

In [11]:
no_rows = df.shape[0]
print(no_rows)

18984

In [12]:
no_cols = df.shape[1]
print(no_cols)

27

In [16]:
no_rows, no_cols = df.shape
print(no_rows)
print(no_cols)

18984
27

In [21]:
#Select POINTID column
id = df["POINTID"]
id

0        47862690
1        47882704
2        47982688
3        48022702
4        48062708
           ...
18979    32643634
18980    32703676
18981    32783608
18982    32783636
18983    33023682
Name: POINTID, Length: 18984, dtype: int64

In [23]:
#Convert previous result(series) into a list
id.to_list()

[47862690,
 47882704,
 47982688,
 48022702,
 48062708,
 48122730,
 48202738,
 48222780,
 48342774,
 48442784,
 48462776,
 48482762,
 46562790,
 46662780,
 46662794,
 46722786,
 46722792,
 46782766,
 46782778,
 46842852,
 46862842,
 46942756,
 46942842,
 46942846,
 46942878,
 46982766,
 47002806,
 47002816,
 47022848,
 47022884,
 47042780,
 47042788,
 47042874,
 47082754,
 47082776,
 47082858,
 47102754,
 47122762,
 47122882,
 47182762,
 47182802,
 47182862,
 47202790,
 47202848,
 47222878,
 47242764,
 47242774,
 47282790,
 47302860,
 47322802,
 47362808,
 47362862,
 47402780,
 47422872,
 47462794,
 47462830,
 47482810,
 47482864,
 47502772,
 47522746,
 47522800,
 47522858,
 47522872,
 47582744,
 47602836,
 47622754,
 47642808,
 47642862,
 47662810,
 47662860,
 47682754,
 47702818,
 47722780,
 47722816,
 47742758,
 47742848,
 47762734,
 47782854,
 47802732,
 47802746,
 47802840,
 47822764,
 47822830,
 47822862,
 47862838,
 47882830,
 47882836,
 47942726,
 47942784,
 47942860,
 47942870,
 47982796,
 47982822,
 47982846,
 47982850,
 48002836,
 48002872,
 48082834,
 48082844,
 48122780,
 48122798,
 48162858,
 48182826,
 48182862,
 48202842,
 48222820,
 48242800,
 48262816,
 48282804,
 48282866,
 45362624,
 45382662,
 45402624,
 45482622,
 45542620,
 45642652,
 45642656,
 45682634,
 45722612,
 45722614,
 45842658,
 45882618,
 45902624,
 45962662,
 46022620,
 46022632,
 46062628,
 46082614,
 46122616,
 46182646,
 46202640,
 46262642,
 46342650,
 46362660,
 46402652,
 46422624,
 46442642,
 46462636,
 46482614,
 46502658,
 46522626,
 46522628,
 46522640,
 46542614,
 46562632,
 46562646,
 46582638,
 46602618,
 46622648,
 46642626,
 46682636,
 46722638,
 46722642,
 46762666,
 46782664,
 46802648,
 46842660,
 46862662,
 46882650,
 46882664,
 46882668,
 46982642,
 46982660,
 47002640,
 47022632,
 47022650,
 47042630,
 47042658,
 47082630,
 46022704,
 46042706,
 46102726,
 46142734,
 46182714,
 46202682,
 46222728,
 46242712,
 46262660,
 46282726,
 46302682,
 46362688,
 46382686,
 46402674,
 46402688,
 46422672,
 46422682,
 46422690,
 46442684,
 46442692,
 46442702,
 46442710,
 46462726,
 46502720,
 46522674,
 46522722,
 46562692,
 46562722,
 46602676,
 46602700,
 46622668,
 46622720,
 46642712,
 46642736,
 46662682,
 46682698,
 46702674,
 46742676,
 46762724,
 46782690,
 46842692,
 46842710,
 46862694,
 46882726,
 46942670,
 46942692,
 46942710,
 46962676,
 46962682,
 46982696,
 47042684,
 47042738,
 47062718,
 47082664,
 47082720,
 47122662,
 47122698,
 47122706,
 47122726,
 47162666,
 47182690,
 47202670,
 47202740,
 47222654,
 47222676,
 47242638,
 47242740,
 47262634,
 47282676,
 47302694,
 47302738,
 47322694,
 47322744,
 47342710,
 47362636,
 47382700,
 47402702,
 47402716,
 47422704,
 47442660,
 47442674,
 47442702,
 47462636,
 47462692,
 47462712,
 47462736,
 47462746,
 47482734,
 47482742,
 47502700,
 47522704,
 47522710,
 47522738,
 47542736,
 47562650,
 47562664,
 47562696,
 47562706,
 47562710,
 47562732,
 47582644,
 47582730,
 47622700,
 47622718,
 47642668,
 47642682,
 47642704,
 47642728,
 47662652,
 47662698,
 47682646,
 47682690,
 47702678,
 47702714,
 47702722,
 47722698,
 47742642,
 47742660,
 47742674,
 47742710,
 47742728,
 47762666,
 47782686,
 47802696,
 47842680,
 47842688,
 27182008,
 27361846,
 27461842,
 27842206,
 28322234,
 28382160,
 28502212,
 28661894,
 28722000,
 45542782,
 45542800,
 45602780,
 45642800,
 45682752,
 45682788,
 45702780,
 45722786,
 45742754,
 45762794,
 45782760,
 45822828,
 45822832,
 45842754,
 45842800,
 45842808,
 45902738,
 45902768,
 45922802,
 45962734,
 45962820,
 45982782,
 46002792,
 46042842,
 46082830,
 46102852,
 46142788,
 46182828,
 46202782,
 46202812,
 46222770,
 46222796,
 46242762,
 46262776,
 46262786,
 46322834,
 46342786,
 46382834,
 46422762,
 46462834,
 46482830,
 46502766,
 46522836,
 46562812,
 46582774,
 46602762,
 46642772,
 46642802,
 46682824,
 46742758,
 46822808,
 46902810,
 45102682,
 45102684,
 45102688,
 45122688,
 45182728,
 45222700,
 45242698,
 45242722,
 45282706,
 45342706,
 45402772,
 45442740,
 45442766,
 45462760,
 45462768,
 45482700,
 45482768,
 45502692,
 45502702,
 45522750,
 45542694,
 45562730,
 45562732,
 45582678,
 45582696,
 45602672,
 45602698,
 45602738,
 45622768,
 45642688,
 45642724,
 45642750,
 45662730,
 45782694,
 45802718,
 45842740,
 45882676,
 45922694,
 46082678,
 46122668,
 46122678,
 43482670,
 43562686,
 43662688,
 43702704,
 43782660,
 43782700,
 43802684,
 43802702,
 43862700,
 43902682,
 43962686,
 44042690,
 44082690,
 44102696,
 44142686,
 44222668,
 44282656,
 44302680,
 44302682,
 44382670,
 44382684,
 44382686,
 44402664,
 44502714,
 44562702,
 44582712,
 44622708,
 44662698,
 44782720,
 44822704,
 44862710,
 44862714,
 44862732,
 44882726,
 44922728,
 44962698,
 45002638,
 45102712,
 45182714,
 45202708,
 45242636,
 45362638,
 42882682,
 42942690,
 42982676,
 43002704,
 43122702,
 43122714,
 43162706,
 43202710,
 43322692,
 43362694,
 39303122,
 39443132,
 39443158,
 39543124,
 39543150,
 39623132,
 39683136,
 39743134,
 39743148,
 39783128,
 39803126,
 39843144,
 39883092,
 39883120,
 39903096,
 39943122,
 39963136,
 40003082,
 40083088,
 40163108,
 40163114,
 38583130,
 38663098,
 38683122,
 38703124,
 38743106,
 38743146,
 38763094,
 38803102,
 38803134,
 38883110,
 38883118,
 38903114,
 38943130,
 38983092,
 38983116,
 39063124,
 39123144,
 39023088,
 39083090,
 39123108,
 39183118,
 39203112,
 39263086,
 39303086,
 39423106,
 39563098,
 39563112,
 39623104,
 39703092,
 39743088,
 39743098,
 39803096,
 38043130,
 38083120,
 38083128,
 38103106,
 38143104,
 38183132,
 38203100,
 38203142,
 38223144,
 38263134,
 38383124,
 38403112,
 38443098,
 38463096,
 38463106,
 38483116,
 38483134,
 38523118,
 38523136,
 38543096,
 38543122,
 39123076,
 39223078,
 39583078,
 39603074,
 38283100,
 38563082,
 38583072,
 38583090,
 38603088,
 38723078,
 38843066,
 38863068,
 38943054,
 39003046,
 39063046,
 39083042,
 39263060,
 39283056,
 39303054,
 39763078,
 39783064,
 39883048,
 39943050,
 40103044,
 40203058,
 40243026,
 40363052,
 40383036,
 40423056,
 40603038,
 39622978,
 39663000,
 39702984,
 39862992,
 40043010,
 40062984,
 40082970,
 40163006,
 40203018,
 39303032,
 39363034,
 39383058,
 39443068,
 39483040,
 39483050,
 39523026,
 39523056,
 39583032,
 39602980,
 39642992,
 39663018,
 39663058,
 39663068,
 39743040,
 39803036,
 39823034,
 53162396,
 53182398,
 53242382,
 53302384,
 53322372,
 53322422,
 53342392,
 53422396,
 53442394,
 53462362,
 53462368,
 53482366,
 53482384,
 53482412,
 53502416,
 53542386,
 53622366,
 53662376,
 53662388,
 53702348,
 53702356,
 53782342,
 53782364,
 53782378,
 53802330,
 53802340,
 53802366,
 53822386,
 53842348,
 53882320,
 53902362,
 53922390,
 53942332,
 53942344,
 53942368,
 53982330,
 54002332,
 54002350,
 54062392,
 54082368,
 54122350,
 54122394,
 54142364,
 54222336,
 54262380,
 54322346,
 54322396,
 54402326,
 54402350,
 54422324,
 54422352,
 54442340,
 54462372,
 54482326,
 54482368,
 54542344,
 54582368,
 54642318,
 54642324,
 54642354,
 54662326,
 54662362,
 54662380,
 54662386,
 54722380,
 54722390,
 54782320,
 54782356,
 54782370,
 54782392,
 54782396,
 54802332,
 54822324,
 54842358,
 54862378,
 54882406,
 54902344,
 54902386,
 54902398,
 54922334,
 55002378,
 55062358,
 55102340,
 55102384,
 55142320,
 55142348,
 55162404,
 55182336,
 55182378,
 55182408,
 55202358,
 55242334,
 55262344,
 55262350,
 55282384,
 55282406,
 55302354,
 55322388,
 55362364,
 55362396,
 55342340,
 55362346,
 55382340,
 55402328,
 55462330,
 55462394,
 55482336,
 55482404,
 55542396,
 55562326,
 55562340,
 55562362,
 55562404,
 55602316,
 55622354,
 55622372,
 55662404,
 55682392,
 55702376,
 55742340,
 55742358,
 55802318,
 55802362,
 55802390,
 55822352,
 55842354,
 55842368,
 55862392,
 55882404,
 55902364,
 55902382,
 55902396,
 55902418,
 55922326,
 55962348,
 55962430,
 56022416,
 56042338,
 56042438,
 56082364,
 56082378,
 56082450,
 56102380,
 56102412,
 56182448,
 56202458,
 56222438,
 56262342,
 56282430,
 56302418,
 56302450,
 56362466,
 56382434,
 56382452,
 56482464,
 56502420,
 56502438,
 56502448,
 56562458,
 56582460,
 56622418,
 56642422,
 56642452,
 56662410,
 56662432,
 56682466,
 56702444,
 56742462,
 56742470,
 56782440,
 56802486,
 56842490,
 56962458,
 57022486,
 57102470,
 57182484,
 57262478,
 56142406,
 56162386,
 56182394,
 56202386,
 56202408,
 56282362,
 56322370,
 56322406,
 56382390,
 56462394,
 56462398,
 56482382,
 56502370,
 56522380,
 56562372,
 56602362,
 56662360,
 56702354,
 56702372,
 56782386,
 56802414,
 56822398,
 56822416,
 56822422,
 56842364,
 56862420,
 56862438,
 56922404,
 56922416,
 57002452,
 57022414,
 57022450,
 57042376,
 57062390,
 57062416,
 57082394,
 57082430,
 57102368,
 57102386,
 57122392,
 57122438,
 57142440,
 57182422,
 57182452,
 57222448,
 57282386,
 57282404,
 57282426,
 57322470,
 57342364,
 57342408,
 57362448,
 57382392,
 57382428,
 57382436,
 57382482,
 57422462,
 57442366,
 57442466,
 57462386,
 57462398,
 57462416,
 57462440,
 57482424,
 57522444,
 57542394,
 57542404,
 57542430,
 57642434,
 57662420,
 57662474,
 57682458,
 57722448,
 57722452,
 57742428,
 57762456,
 57802466,
 57822440,
 57842460,
 57842474,
 55602298,
 55682262,
 55682266,
 55722274,
 55722292,
 55742250,
 55742290,
 55862266,
 55902264,
 55922296,
 56002258,
 56002286,
 56042258,
 56082288,
 56102260,
 56142258,
 56142276,
 56162290,
 56202314,
 56282268,
 56302302,
 56322276,
 56402320,
 56422290,
 56442264,
 56462260,
 56482284,
 56482306,
 56562290,
 56562344,
 56642296,
 56662338,
 56682268,
 56722276,
 56742272,
 56782268,
 56802310,
 56802342,
 56842256,
 56842292,
 56842320,
 56862298,
 56862330,
 56902250,
 56902276,
 56922264,
 56942334,
 56962314,
 57022266,
 57022320,
 57062336,
 57102282,
 57122302,
 57122330,
 57122348,
 57142286,
 57162300,
 57162364,
 57242282,
 57242300,
 57262276,
 57302330,
 57322286,
 57362326,
 57422350,
 57442294,
 57442340,
 57482360,
 57522354,
 57542296,
 57542308,
 57702274,
 29042168,
 53402272,
 53442258,
 53462246,
 53462264,
 53482214,
 53482276,
 53502218,
 53522226,
 53562216,
 53582236,
 53582250,
 53602270,
 53702212,
 53702216,
 53702240,
 53702262,
 53702276,
 53722304,
 53742220,
 53742228,
 53742300,
 53742306,
 53742310,
 53762196,
 53762206,
 53782270,
 53802244,
 53802286,
 53822218,
 53822252,
 53822288,
 53842226,
 53842316,
 53862218,
 53862246,
 53882194,
 53882222,
 53882230,
 53882234,
 53882276,
 53882284,
 53882288,
 53902178,
 53902242,
 53902268,
 53922288,
 53942254,
 53962180,
 53962194,
 53962198,
 53982204,
 53982258,
 54022244,
 54022258,
 54022304,
 54022312,
 54042174,
 54062198,
 54062230,
 54062288,
 54102148,
 54102180,
 54102198,
 54102246,
 54102324,
 54122308,
 54122326,
 54142176,
 54142248,
 54162172,
 54162190,
 54182138,
 54182272,
 54202132,
 54202178,
 54222134,
 54222236,
 54222278,
 54282144,
 54282238,
 54282252,
 54302142,
 54322284,
 54342240,
 54362138,
 54382196,
 54382232,
 54402264,
 54402308,
 54422140,
 54422204,
 ...]

In [27]:
#Filter dataframe and select only the columns needed
# Columns needed are: POINTID, OC, P, TH_LAT, TH_LONG, Elev, LU1_Desc
sel_df = df[["POINTID", "OC", "P", "TH_LAT", "TH_LONG", "Elev", "LU1_Desc"]] 
sel_df

,POINTID,OC,P,TH_LAT,TH_LONG,Elev,LU1_Desc
0,47862690,12.4,< LOD,47.150238,16.134212,291,Forestry
1,47882704,16.7,< LOD,47.274272,16.175359,373,Forestry
2,47982688,47.5,12.3,47.123260,16.289693,246,Forestry
3,48022702,28.1,< LOD,47.245693,16.357506,305,Forestry
4,48062708,19.4,< LOD,47.296372,16.416782,335,Forestry
...,...,...,...,...,...,...,...
18979,32643634,51.4,92.2,54.713343,-6.563749,50,Agriculture (excluding fallow land and kitchen...
18980,32703676,73.9,81.6,55.091488,-6.625119,34,Agriculture (excluding fallow land and kitchen...
18981,32783608,63.7,101.9,54.515104,-6.259448,50,Agriculture (excluding fallow land and kitchen...
18982,32783636,38.3,7.3,54.759266,-6.358608,122,Residential
18983,33023682,98.7,33.7,55.208730,-6.156597,143,Agriculture (excluding fallow land and kitchen...

In [30]:
sel_df.head(n = 10)

,POINTID,OC,P,TH_LAT,TH_LONG,Elev,LU1_Desc
0,47862690,12.4,< LOD,47.150238,16.134212,291,Forestry
1,47882704,16.7,< LOD,47.274272,16.175359,373,Forestry
2,47982688,47.5,12.3,47.123260,16.289693,246,Forestry
3,48022702,28.1,< LOD,47.245693,16.357506,305,Forestry
4,48062708,19.4,< LOD,47.296372,16.416782,335,Forestry
5,48122730,18,68,47.488817,16.520595,232,Agriculture (excluding fallow land and kitchen...
6,48202738,12.5,58.1,47.554102,16.635559,283,Agriculture (excluding fallow land and kitchen...
7,48222780,22.9,17.5,47.928696,16.711158,136,Agriculture (excluding fallow land and kitchen...
8,48342774,29.1,62.2,47.865059,16.863852,115,Agriculture (excluding fallow land and kitchen...
9,48442784,14.4,< LOD,47.946158,17.009260,166,Agriculture (excluding fallow land and kitchen...

In [34]:
elevation = sel_df["Elev"]
elevation

0        291
1        373
2        246
3        305
4        335
        ...
18979     50
18980     34
18981     50
18982    122
18983    143
Name: Elev, Length: 18984, dtype: int64

In [ ]:
import numpy as np
def m_to_km(elevation):
    """
    Converts elevation measurements from meters to kilometers.

    This function handles missing topographical data by checking for 
    null values (NaN) before performing the division. This prevents 
    calculation errors in environmental modeling datasets.

    Args:
        elevation (float or int): The altitude/elevation value in meters.
            Can also be a np.nan or None.

    Returns:
        float: The elevation converted to kilometers (elevation / 1000).
        np.nan: If the input elevation was missing or null.

    Example:
        >>> m_to_km(1500)
        1.5
        >>> m_to_km(None)
        nan
    """
    if pd.isna(elevation): #If it is null
        return np.nan
    return elevation / 1000

In [52]:
m_to_km(28)

0.028

In [ ]:
#Convert everything in the Elev column from meters to km
#Using .apply() 
elev_km = sel_df["Elev"].apply(m_to_km)
elev_km

0        0.291
1        0.373
2        0.246
3        0.305
4        0.335
         ...
18979    0.050
18980    0.034
18981    0.050
18982    0.122
18983    0.143
Name: Elev, Length: 18984, dtype: float64

In [ ]:
#Replace the old values of Elev with the new ones in the "sel_df" data frame
sel_df["Elev"] = sel_df["Elev"].apply(m_to_km)

C:\Users\Victus\AppData\Local\Temp\ipykernel_45768\1318520468.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sel_df["Elev"] = sel_df["Elev"].apply(m_to_km)

In [59]:
sel_df

,POINTID,OC,P,TH_LAT,TH_LONG,Elev,LU1_Desc
0,47862690,12.4,< LOD,47.150238,16.134212,2.910000e-07,Forestry
1,47882704,16.7,< LOD,47.274272,16.175359,3.730000e-07,Forestry
2,47982688,47.5,12.3,47.123260,16.289693,2.460000e-07,Forestry
3,48022702,28.1,< LOD,47.245693,16.357506,3.050000e-07,Forestry
4,48062708,19.4,< LOD,47.296372,16.416782,3.350000e-07,Forestry
...,...,...,...,...,...,...,...
18979,32643634,51.4,92.2,54.713343,-6.563749,5.000000e-08,Agriculture (excluding fallow land and kitchen...
18980,32703676,73.9,81.6,55.091488,-6.625119,3.400000e-08,Agriculture (excluding fallow land and kitchen...
18981,32783608,63.7,101.9,54.515104,-6.259448,5.000000e-08,Agriculture (excluding fallow land and kitchen...
18982,32783636,38.3,7.3,54.759266,-6.358608,1.220000e-07,Residential
18983,33023682,98.7,33.7,55.208730,-6.156597,1.430000e-07,Agriculture (excluding fallow land and kitchen...

In [66]:
#Create a new column by the sum of Lat and Long
def lat_sum_long(lat, long):
    """
    Sums up the value of the latitude and longitude in each row.

    This function deals with missing lat and long values
    by checking for Null values (NaN) before carrying out the sum operation
    and ensures that calculation errors are prevented

    Args:
        Latitude and longitude values (float or integer)
            Can also be a np.nan or None.
    
    Returns:
        float: sum of lat and long values
        np.nan: If the lat or long value was missing or null.
    
    Example:
        >>> lat_sum_long(2, 5)
        7
        >>> lat_sum_long(None, None)
        nan
    """
    if pd.isna(lat) or pd.isna(long):
        return np.nan
    return lat + long

In [67]:
sel_df["sum_coords"] = sel_df.apply(lambda row: lat_sum_long(row.TH_LAT, row.TH_LONG), axis = 1)

C:\Users\Victus\AppData\Local\Temp\ipykernel_45768\3717998913.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sel_df["sum_coords"] = sel_df.apply(lambda row: lat_sum_long(row.TH_LAT, row.TH_LONG), axis = 1)

In [69]:
sel_df

,POINTID,OC,P,TH_LAT,TH_LONG,Elev,LU1_Desc,sum_coords
0,47862690,12.4,< LOD,47.150238,16.134212,2.910000e-07,Forestry,63.284450
1,47882704,16.7,< LOD,47.274272,16.175359,3.730000e-07,Forestry,63.449631
2,47982688,47.5,12.3,47.123260,16.289693,2.460000e-07,Forestry,63.412953
3,48022702,28.1,< LOD,47.245693,16.357506,3.050000e-07,Forestry,63.603199
4,48062708,19.4,< LOD,47.296372,16.416782,3.350000e-07,Forestry,63.713153
...,...,...,...,...,...,...,...,...
18979,32643634,51.4,92.2,54.713343,-6.563749,5.000000e-08,Agriculture (excluding fallow land and kitchen...,48.149594
18980,32703676,73.9,81.6,55.091488,-6.625119,3.400000e-08,Agriculture (excluding fallow land and kitchen...,48.466369
18981,32783608,63.7,101.9,54.515104,-6.259448,5.000000e-08,Agriculture (excluding fallow land and kitchen...,48.255656
18982,32783636,38.3,7.3,54.759266,-6.358608,1.220000e-07,Residential,48.400658
18983,33023682,98.7,33.7,55.208730,-6.156597,1.430000e-07,Agriculture (excluding fallow land and kitchen...,49.052133

In [70]:
#Reorder the columns in the "sel_df" dataframe
sel_df = sel_df[["POINTID", "OC", "P", "TH_LAT", "TH_LONG", "sum_coords", "Elev", "LU1_Desc"]]

In [71]:
sel_df

,POINTID,OC,P,TH_LAT,TH_LONG,sum_coords,Elev,LU1_Desc
0,47862690,12.4,< LOD,47.150238,16.134212,63.284450,2.910000e-07,Forestry
1,47882704,16.7,< LOD,47.274272,16.175359,63.449631,3.730000e-07,Forestry
2,47982688,47.5,12.3,47.123260,16.289693,63.412953,2.460000e-07,Forestry
3,48022702,28.1,< LOD,47.245693,16.357506,63.603199,3.050000e-07,Forestry
4,48062708,19.4,< LOD,47.296372,16.416782,63.713153,3.350000e-07,Forestry
...,...,...,...,...,...,...,...,...
18979,32643634,51.4,92.2,54.713343,-6.563749,48.149594,5.000000e-08,Agriculture (excluding fallow land and kitchen...
18980,32703676,73.9,81.6,55.091488,-6.625119,48.466369,3.400000e-08,Agriculture (excluding fallow land and kitchen...
18981,32783608,63.7,101.9,54.515104,-6.259448,48.255656,5.000000e-08,Agriculture (excluding fallow land and kitchen...
18982,32783636,38.3,7.3,54.759266,-6.358608,48.400658,1.220000e-07,Residential
18983,33023682,98.7,33.7,55.208730,-6.156597,49.052133,1.430000e-07,Agriculture (excluding fallow land and kitchen...

Filtering Rows

In [78]:
#Filtering can be done using "iloc" with the integer index
sel_df.iloc[1, :] #row index = 1 and all columns

POINTID        47882704
OC                 16.7
P                 < LOD
TH_LAT        47.274272
TH_LONG       16.175359
sum_coords    63.449631
Elev                0.0
LU1_Desc       Forestry
Name: 1, dtype: object

In [90]:
# all rows from index=1 to index=9 and all columns
sel_df.iloc[1 : 10, :]

,POINTID,OC,P,TH_LAT,TH_LONG,sum_coords,Elev,LU1_Desc
1,47882704,16.7,< LOD,47.274272,16.175359,63.449631,3.730000e-07,Forestry
2,47982688,47.5,12.3,47.123260,16.289693,63.412953,2.460000e-07,Forestry
3,48022702,28.1,< LOD,47.245693,16.357506,63.603199,3.050000e-07,Forestry
4,48062708,19.4,< LOD,47.296372,16.416782,63.713153,3.350000e-07,Forestry
5,48122730,18,68,47.488817,16.520595,64.009412,2.320000e-07,Agriculture (excluding fallow land and kitchen...
6,48202738,12.5,58.1,47.554102,16.635559,64.189661,2.830000e-07,Agriculture (excluding fallow land and kitchen...
7,48222780,22.9,17.5,47.928696,16.711158,64.639853,1.360000e-07,Agriculture (excluding fallow land and kitchen...
8,48342774,29.1,62.2,47.865059,16.863852,64.728911,1.150000e-07,Agriculture (excluding fallow land and kitchen...
9,48442784,14.4,< LOD,47.946158,17.009260,64.955418,1.660000e-07,Agriculture (excluding fallow land and kitchen...

In [91]:
# all rows from index=0 to index=5 and just the sum_coords column 
sel_df.iloc[1 : 6, 5]

1    63.449631
2    63.412953
3    63.603199
4    63.713153
5    64.009412
Name: sum_coords, dtype: float64

In [92]:
#Instead of integer index, use the labels and "loc" method
sel_df.loc[0 : 5, "sum_coords"]

0    63.284450
1    63.449631
2    63.412953
3    63.603199
4    63.713153
5    64.009412
Name: sum_coords, dtype: float64

In [ ]:
#Filter rows using a condition
sel_df["sum_coords"] > 63

0         True
1         True
2         True
3         True
4         True
         ...
18979    False
18980    False
18981    False
18982    False
18983    False
Name: sum_coords, Length: 18984, dtype: bool

In [104]:
#Filter rows that have a sum_coords greater than 86, while also showing their respective POINTID, OD, and LU1_Dec columns
sel_df.loc[sel_df["sum_coords"] > 86, ["POINTID", "OC", "LU1_Desc"]]

        POINTID     OC                                           LU1_Desc
2727   52564144   19.3                                           Forestry
2734   52624148   10.4  Agriculture (excluding fallow land and kitchen...
2738   52664136     39                                           Forestry
2744   52744126  220.5                                           Forestry
2755   52804152   17.1  Agriculture (excluding fallow land and kitchen...
...         ...    ...                                                ...
18171  49444846     95                                           Forestry
18172  49504810  470.9          Semi-natural and natural areas not in use
18173  52764680     10                                           Forestry
18286  53024568  207.5                                           Forestry
18503  53464576  518.1                                           Forestry

[1103 rows x 3 columns]